// to reuse
const textureList = [
  {
    id: "1",
    name: "Wood 1",
    map: "./texture/wood1.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "2",
    name: "Wood 2",
    map: "./texture/wood2.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "3",
    name: "Wood 3",
    map: "./texture/wood3.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "4",
    name: "Wood 4",
    map: "./texture/wood4.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "5",
    name: "Wood 5",
    map: "./texture/wood5.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "6",
    name: "Wood 6",
    map: "./texture/wood6.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "7",
    name: "Wood 7",
    map: "./texture/wood7.webp",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "8",
    name: "Wood 8",
    map: "./texture/wood8.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "9",
    name: "linen 1",
    map: "./texture/linen1.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "10",
    name: "linen 2",
    map: "./texture/linen2.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "11",
    name: "linen 3",
    map: "./texture/linen3.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "12",
    name: "linen 4",
    map: "./texture/linen4.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "13",
    name: "marble 1",
    map: "./texture/marble1.webp",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "14",
    name: "marble 2",
    map: "./texture/marble2.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "15",
    name: "marble 3",
    map: "./texture/marble3.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "16",
    name: "parquet 1",
    map: "./texture/parquet1.webp",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
];

export const ProductList = {
  floor: {
    id: 1,
    name: "Floor",
    textures: [
      textureList[0],
      textureList[1],
      textureList[2],
      textureList[3],
      textureList[4],
      textureList[5],
      textureList[6],
      textureList[7],
      textureList[12],
      textureList[13],
      textureList[14],
      textureList[15],
    ],
  },
  table: {
    id: 1,
    name: "Table",
    textures: [
      textureList[0],
      textureList[1],
      textureList[2],
      textureList[3],
      textureList[4],
      textureList[7],
    ],
  },
  cabinet: {
    id: 1,
    name: "Cabinet",
    textures: [
      textureList[1],
      textureList[2],
      textureList[3],
      textureList[5],
      textureList[7],
    ],
  },
  carpet: {
    id: 1,
    name: "Carpet",
    textures: [
      textureList[8],
      textureList[9],
      textureList[10],
      textureList[11],
    ],
  },
};
