// to reuse
const textureList = [
  {
    id: "1",
    name: "Birch Breeze",
    map: "./texture/wood1.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "2",
    name: "Maple Drift",
    map: "./texture/wood2.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "3",
    name: "Pine Tranquility",
    map: "./texture/wood3.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "4",
    name: "Oak Reverie",
    map: "./texture/wood4.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "5",
    name: "Walnut Wisp",
    map: "./texture/wood5.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "6",
    name: "Driftwood Dune",
    map: "./texture/wood6.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "7",
    name: "Hickory Haze",
    map: "./texture/wood7.webp",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "8",
    name: "Sable Strata",
    map: "./texture/wood8.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "9",
    name: "Amber Drift",
    map: "./texture/linen1.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "10",
    name: "Woven Whispers",
    map: "./texture/linen2.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 20,
    repeatY: 20,
  },
  {
    id: "11",
    name: "Slate Ripple",
    map: "./texture/linen3.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "12",
    name: "Rustic Charm",
    map: "./texture/linen4.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "13",
    name: "Ocean Wave",
    map: "./texture/marble1.webp",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "14",
    name: "Rosette Veil",
    map: "./texture/marble2.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 16,
    repeatY: 16,
  },
  {
    id: "15",
    name: "Celestial Rift",
    map: "./texture/marble3.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 40,
    repeatY: 40,
  },
  {
    id: "16",
    name: "Geometric Prism",
    map: "./texture/parquet1.webp",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 16,
    repeatY: 16,
  },
  {
    id: "17",
    name: "Celestial Flow",
    map: "./texture/wallpaper1.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 20,
    repeatY: 30,
  },
  {
    id: "18",
    name: "Golden Whirl",
    map: "./texture/wallpaper2.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 30,
    repeatY: 30,
  },
  {
    id: "19",
    name: "Quartz Horizon",
    map: "./texture/wallpaper3.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 20,
    repeatY: 20,
  },
  {
    id: "20",
    name: "Opal Fragments",
    map: "./texture/wallpaper4.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 20,
    repeatY: 20,
  },
  {
    id: "21",
    name: "Mystic Ripple",
    map: "./texture/wallpaper5.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 12,
    repeatY: 12,
  },
  {
    id: "22",
    name: "Nebula Diamond",
    map: "./texture/wallpaper6.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 20,
    repeatY: 20,
  },

  {
    id: "24",
    name: "Dusky Concrete",
    map: "./texture/concrete1.jpg",
    color: "#ffffff",
    metalness: 0.00001,
    roughness: 0.672727,
    repeatX: 30,
    repeatY: 30,
  },
];

export const ProductList = {
  floor: {
    id: 1,
    name: "Floor",
    textures: [
      textureList[1],
      textureList[2],
      textureList[3],
      textureList[4],
      textureList[5],
      textureList[6],
      textureList[7],
      textureList[12],
      textureList[13],
      textureList[14],
      textureList[15],
    ],
  },
  table: {
    id: 1,
    name: "Table",
    textures: [
      textureList[0],
      textureList[1],
      textureList[2],
      textureList[3],
      textureList[4],
      textureList[7],
    ],
  },
  cabinet: {
    id: 1,
    name: "Cabinet",
    textures: [
      textureList[1],
      textureList[2],
      textureList[3],
      textureList[5],
      textureList[7],
    ],
  },
  carpet: {
    id: 1,
    name: "Carpet",
    textures: [
      textureList[8],
      textureList[9],
      textureList[10],
      textureList[11],
    ],
  },
  kitchen: {
    id: 1,
    name: "Wardrobe",
    textures: [
      textureList[1],
      textureList[2],
      textureList[3],
      textureList[5],
      textureList[7],
    ],
  },
  wallsL: {
    id: 1,
    name: "walls",
    textures: [
      textureList[16],
      textureList[17],
      textureList[18],
      textureList[19],
      textureList[20],
      textureList[21],
      textureList[22],
    ],
  },
  wallsR: {
    id: 1,
    name: "walls",
    textures: [
      textureList[16],
      textureList[17],
      textureList[18],
      textureList[19],
      textureList[20],
      textureList[21],
      textureList[22],
    ],
  },
  wallsF: {
    id: 1,
    name: "walls",
    textures: [
      textureList[16],
      textureList[17],
      textureList[18],
      textureList[19],
      textureList[20],
      textureList[21],
      textureList[22],
    ],
  },
  wallsB: {
    id: 1,
    name: "walls",
    textures: [
      textureList[16],
      textureList[17],
      textureList[18],
      textureList[19],
      textureList[20],
      textureList[21],
      textureList[22],
    ],
  },
  chairs: {
    id: 1,
    name: "Chair",
    textures: [
      textureList[8],
      textureList[9],
      textureList[10],
      textureList[11],
      textureList[16],
      textureList[17],
      textureList[18],
      textureList[19],
      textureList[20],
      textureList[21],
      textureList[22],
    ],
  },
  blinders: {
    id: 1,
    name: "Blinder",
    textures: [
      textureList[1],
      textureList[2],
      textureList[3],
      textureList[4],
      textureList[5],
      textureList[6],
      textureList[7],
      textureList[8],
      textureList[9],
      textureList[10],
      textureList[11],
    ],
  },
};
